force-app/main/default/objects/Job__c/Job__c.object-meta.xml
<CustomObject>
    <label>Job</label>
    <nameField>
        <displayFormat>J-{0000}</displayFormat>
        <label>Job Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Job__c/fields/Expiry_Date__c.field-meta.xml
<CustomField>
    <fullName>Expiry_Date__c</fullName>
    <formula>Creation_Date__c + Validity_Period_Days__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Expiry Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Job_Description__c.field-meta.xml
<CustomField>
    <fullName>Job_Description__c</fullName>
    <label>Job Description</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Number_of_Vacc__c.field-meta.xml
<CustomField>
    <fullName>Number_of_Vacc__c</fullName>
    <label>Number of Vacancies</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Job__c/fields/Validity__c.field-meta.xml
<CustomField>
    <fullName>Validity__c</fullName>
    <label>Validity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Active</fullName>
            </value>
            <value>
                <fullName>Expired</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Job__c/fields/Validity_Period_Days__c.field-meta.xml
<CustomField>
    <fullName>Validity_Period_Days__c</fullName>
    <label>Validity Period(Days)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/JobListController.cls
public with sharing class JobListController {
    @AuraEnabled(Cacheable=true)
    public static List<Job__c> getAllJobs() {
        return[SELECT Name, Company_Name__c, Creation_Date__c, Expiry_Date__c, Job_Description__c, Job_Type__c,  Job_Position__c , Number_of_Vacc__c, Validity_Period_Days__c, Validity__c 
            FROM Job__c WHERE Validity__c = 'Active'];

    }


    @AuraEnabled(Cacheable=true)
    public static List<Job__c> searchJobs(String searchTerm) {
        searchTerm = searchTerm.trim();
        if (searchTerm == '') {
            return getAllJobs();
        }
        searchTerm = '%' + searchTerm + '%';
        return [
            SELECT Name, Company_Name__c, Job_Type__c,  Job_Position__c , Number_of_Vacc__c
             FROM Job__c WHERE Validity__c = 'Active' AND Job_Type__c LIKE :searchTerm
            ORDER BY Name ASC
            LIMIT 50
        ];
    }
}    