force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience_Detail__c/Experience_Detail__c.object-meta.xml
<CustomObject>
    <label>Experience Detail</label>
    <nameField>
        <displayFormat>Exp-{0000}</displayFormat>
        <label>Experience Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Experience Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Experience_Detail__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Experience Details</relationshipLabel>
    <relationshipName>Experience_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Experience_Detail__c/fields/Job_Type__c.field-meta.xml
<CustomField>
    <fullName>Job_Type__c</fullName>
    <label>Job Type</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Experience_Detail__c/fields/Period__c.field-meta.xml
<CustomField>
    <fullName>Period__c</fullName>
    <formula>YEAR(End_Date__c)- YEAR(Start_Date__c)+ (End_Date__c - DATE(YEAR(End_Date__c),MONTH(Start_Date__c),DAY(Start_Date__c)))/365</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Period(Years)</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/ExperienceDetailController.cls
public with sharing class ExperienceDetailController {  
    @AuraEnabled
    public static List<Experience_Detail__c> getExperienceDetail(id appId) {
        return [SELECT  Job_Type__c, Company_Name__c, End_Date__c, Start_Date__c, Period__c FROM Experience_Detail__c WHERE Applicant__c = :appId];

    }
     @AuraEnabled
    public static List<Applicant__c> getApplciantId(id appId){
        return [SELECT  Name FROM Applicant__c WHERE Id = :appId];
    }

}