force-app/main/default/objects/Applicant__c/Applicant__c.object-meta.xml
<CustomObject>
    <label>Applicant</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>Applicant Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Applicants</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Detail__c/Education_Detail__c.object-meta.xml
<CustomObject>
    <label>Education Detail</label>
    <nameField>
        <displayFormat>E-{0000}</displayFormat>
        <label>Education Detail Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Education Details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Education_Detail__c/fields/Applicant__c.field-meta.xml
<CustomField>
    <fullName>Applicant__c</fullName>
    <label>Applicant</label>
    <referenceTo>Applicant__c</referenceTo>
    <relationshipLabel>Education Details</relationshipLabel>
    <relationshipName>Education_Details</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Education_Detail__c/fields/Degree__c.field-meta.xml
<CustomField>
    <fullName>Degree__c</fullName>
    <label>Degree</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Education_Detail__c/fields/Institution__c.field-meta.xml
<CustomField>
    <fullName>Institution__c</fullName>
    <label>Institution</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EducationDetailController.cls
public with sharing class EducationDetailController {
     @AuraEnabled
    public static List<Education_Detail__c> getEducationDetail(id appId) {
        return [SELECT  Degree__c, Institution__c, Start_Date__c, End_Date__c FROM Education_Detail__c WHERE Applicant__c = :appId];

    }

    @AuraEnabled(cacheable=true)
    public static String deleteEducation(id eduId) {
    
        Education_Detail__c[] eduList = [SELECT  Degree__c, Institution__c, Start_Date__c, End_Date__c FROM Education_Detail__c  WHERE Id = :eduId];   
        delete eduList;
        return 'Record Sucessfully deleted';
        
    }
}